### ISSUE TITLE
GLX context error when starting Steam

### ISSUE THREAD

**Issue by ubuntudroid** [ozonos/bug-tracker-BETA#15]
Upon starting steam I get the following error message (can still continue afterwards, but haven't tried to start a game yet):

"OpenGL GLX context is not using direct rendering, which may cause performance problems.
For more information visit https://support.steampowered.com/kb_article.php?ref=9938-EYZB-7457."

Following the steps outlined on the linked support page I could find no apparent issues. I've not yet installed the proprietary Nvidia drivers as I was curious about the performance without using them. There also doesn't seem to be a graphical installer for getting proprietary drivers as of now.

System specs:
Intel Core i7-4770K CPU, 16 GB RAM, Nvidia GTX 780, 240 GB HDD

**Comment by matthewlswanson** [comment]
I got the same issue, I could not get a game to play either. Will try on a different system.

**Comment by UriHerrera** [comment]
According to questions about this error (because it is a Steam error not an error of the system) it's because one of two things:

* Steam uses older `gcc` libraries and you should remove them:
`libstdc++.so`
`libgcc_s.so`
`ibgcc_s.so`
`libstdc++.so`
`libxcb.so`

You should find those libraries in the Steam path.

* Your user does not belong to the group `video` so you have to add it.

**Comment by ubuntudroid** [comment]
@UriHerrera Thanks a lot! Removing `libstdc++.so.6` and `libstdc++.so.6.0.18` from `/home/<username>/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu` worked like a charm!

For everyone interested in the underlying bug, check out [this page](https://github.com/ValveSoftware/steam-for-linux/issues/3273).
