### ISSUE TITLE
Notification stuck behind Atom Dock

### ISSUE THREAD

**Issue by matthewlswanson** [ozonos/bug-tracker-BETA#16]
All my notification pop up behind the Atom Dock and the only way I can view them is to disable the Atom Dock

**Comment by cldx** [comment]
This is sadly pretty inconvenient to fix from the Dock Side of things. We have the atom-notifications Extension for this. I understand this is not really modular. But the Notification Adjustments are just too much to handle all in the Dock Code. So it is recommended to use Atom Notifications alongside the Dock.

Maybe at one point we will have a better handling for Notifications but right now that's the way to go.

Also, if you KNOW the bug is related to the extensions you can just file a bug at the extension repo and not in the Beta Tracker. That would be thankfully apprecciated.

**Comment by cldx** [comment]
Let's move this to [Atom Dock](https://github.com/ozonos/atom-dock/issues/53) so we can close this.
